// entrypoints/components/Login.jsx
import {Anchor, Button, Container, Group, Paper, TextInput, Title,} from '@mantine/core';
import {useValidatedState} from '@mantine/hooks';
import BaseUtils from 'validator/es';
import {toast} from 'react-toastify';

export function Login() {
  const isValidCode = (code) => {
    return !BaseUtils.isEmpty(code) && code.length >= 4;
  }

  const [email, setEmail] = useValidatedState(
    '',
    (val) => BaseUtils.isEmail(val),
    true
  );
  const [code, setCode] = useValidatedState(
    '',
    (val) => isValidCode(val),
    true
  );

  const sendCode = () => {
    if (!BaseUtils.isEmail(email.value)) {
      toast.error('Email is not valid');
      return;
    }
    browser.runtime.sendMessage({action: VERIFY_EMAIL, email: email.value}).then(response => {
      if (!response.done) {
        toast.error('Sending code failed. Please try again later');
      } else {
        toast.success('Verification code is sent to your email.');
      }
      return true;
    });
  }

  const login = () => {
    if (!BaseUtils.isEmail(email.value) || !isValidCode(code.value)) {
      toast.error('Email or code is not valid');
      return;
    }
    browser.runtime.sendMessage({
      action: LOGIN, user: {
        email: email.value, token: code.value
      }
    }).then(response => {
      if (!response.done) {
        toast.error('SignIn failed. Please try again later');
      }
      return true;
    });
  }
  return (
    <Container w={380}>
      <Title ta="center" fw={900} mt="md" mb={10} style={{
        fontFamily: 'Greycliff CF, var(--mantine-font-family)'
      }}>
        Join Shark Eagle Note
      </Title>

      <Paper withBorder shadow="md" p={30} mt={30} radius="md">
        <TextInput label="Email" placeholder="you@example.com" required
                   description="We'll never share your email with anyone else."
                   inputWrapperOrder={['label', 'error', 'input', 'description']}
                   value={email.value}
                   withAsterisk
                   error={!email.valid}
                   onChange={(event) => setEmail(event.currentTarget.value)}
        />
        <TextInput label="Verification Code" placeholder="Click link below to receive the code"
                   required mt="md"
                   value={code.value}
                   withAsterisk
                   error={!code.valid}
                   onChange={(event) => setCode(event.currentTarget.value)}/>
        <Group justify="space-between" mt="lg">
          <Anchor component="button" size="sm" onClick={sendCode}>
            * Send verification code to email
          </Anchor>
        </Group>
        <Button fullWidth mt="xl" onClick={login} disabled={!isValidCode(code.value)}>
          Sign in
        </Button>
      </Paper>
    </Container>
  );
}

// src/overlay/components/Login.vue
<template>
  <div class="user-form">
    <img class="mb-4 saltynote-logo" :src="iconUrl" alt="" width="72" height="72" />
    <h1 class="h3 mb-3 font-weight-normal">Please Login</h1>

    <div class="form-group">
      <input type="email" class="form-control" v-model="user.email" placeholder="Your Email" aria-describedby="emailHelp" />
      <small id="emailHelp" class="form-text text-muted text-left">We'll never share your email with anyone else.</small>
    </div>

    <div class="form-group input-group">
      <input type="text" class="form-control" v-model="user.token" placeholder="Verification Code" />
      <div class="input-group-append">
        <button class="btn btn-outline-primary" type="button" @click="sendCode">Send Code</button>
      </div>
    </div>

    <button class="btn btn-lg btn-primary btn-block" @click="signIn">SignIn</button>
  </div>
</template>

<script>
import * as BaseUtils from '../../utils/base';
import toastr from 'toastr';
import * as types from '../../utils/action-types';
import 'toastr/build/toastr.min.css';

export default {
  name: 'Login',
  data() {
    return {
      user: {
        email: '',
        token: '',
      },
      iconUrl: chrome.runtime.getURL('icons/icon.png'),
    };
  },
  created() {
    toastr.options.progressBar = true;
  },
  methods: {
    sendCode() {
      if (!BaseUtils.isEmail(this.user.email)) {
        toastr.error('Email is not valid', 'SaltyNote');
      }

      toastr.info('Processing, please wait...');

      chrome.runtime.sendMessage({ action: types.VERIFY_EMAIL, email: this.user.email }, response => {
        if (!response.done) {
          toastr.error('Sending code failed. Please try again later');
        } else {
          toastr.success('Verification code is sent to your email.');
        }
        return true;
      });
    },
    signIn() {
      if (!BaseUtils.isEmail(this.user.email)) {
        toastr.error('Email is not valid', 'SaltyNote');
        return;
      }
      if (!this.user.token) {
        toastr.error('Email verification code is required', 'SaltyNote');
        return;
      }
      chrome.runtime.sendMessage({ action: types.LOGIN, user: this.user }, response => {
        if (!response.done) {
          toastr.error('SignIn failed. Please try again later');
        }
        return true;
      });
    },
  },
};
</script>

<style scoped lang="scss">
.user-form {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
  text-align: center;

  img.saltynote-logo {
    margin: auto;
  }

  .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }

  p {
    color: #454343;
  }

  .link-mouse {
    cursor: pointer;
    text-decoration: none;
  }
}
</style>
