// entrypoints/content/components/NoAnnotationPlaceholder.jsx
import {Card, Container, Image, Paper, Text} from '@mantine/core';
import notFoundImage from '/public/icon/notfound.png';
import {useState} from 'react';

function NoAnnotationPlaceholder() {
  const [count, setCount] = useState(0);
  return (

    <Container w={380}>
      <Paper withBorder shadow="md" mt={30} radius="md">
        <Card>
          <Image src={notFoundImage} alt="No Note Found"/>
          <Text c='blue' mt={5} ta='center'>
            You do not have any annotation for this page! ;-)
          </Text>
        </Card>
      </Paper>
    </Container>
  );
}

export default NoAnnotationPlaceholder;

// src/overlay/components/NoAnnotationPlaceholder.vue
<template>
  <div class="card">
    <img class="card-img-top" :src="image" alt="Card cap" />
    <div class="card-body text-center">
      <h5 class="card-title">You do not have any notes for this page! ;-)</h5>
    </div>
  </div>
</template>

<script>
export default {
  name: 'NoAnnotationPlaceholder',
  data() {
    return {
      image: chrome.runtime.getURL('icons/dog.jpg'),
    };
  },
};
</script>
